### ISSUE TITLE
Remove "Where is this running?" and "A web frontend for getML" Section

### ISSUE THREAD

**Issue by Jogala** [getml/getml-demo#15]
In all the notebooks, there is a "Where is this running?" and "A web frontend for getML
" section. 

https://notebooks.getml.com/github/getml/getml-demo/blob/master/interstate94.ipynb

Both seem very confusing, I think they should be removed. The link in "You can launch the getML monitor [here](http://localhost:1709/)" is not getting resolved on the website!

Add hint in the beginning of the website where the notebook is displayed (not part of the notebook), that tells the user that he can run the notebook by pressing the 3 Rings in the top right corner (Execute on binder).

**Comment by Urfoex** [comment]
Section removal in PR: [https://github.com/getml/getml-demo/pull/17](https://github.com/getml/getml-demo/pull/17)
