### ISSUE TITLE
Comparisons with TSFresh but where are the extracted timeseries features?

### ISSUE THREAD

**Issue by CapitalMarkets** [getml/getml-demo#23]
Quite simply, TSFresh provides very useful functions for many timeseries analysis needs - the issue with it is that it is very SLOOOOWWWWW.

What I'm struggling to understand about this getML, after clicking through pages of documentation, is how it compares to TSFresh which it is always comparing itself with.

These extracted time series features are what draw people to TSFresh:
https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html

Is getML generating the same?
If so, where are these documented?

Many thanks.

**Comment by liuzicheng1987** [comment]
@CapitalMarkets , thanks for the request. 

getML and tsfresh do not produce the exact same features. There are some that we have and they don't and vice versa. But there also is a large overlap.

**Comment by liuzicheng1987** [comment]
@CapitalMarkets , for a complete overview, please refer to our documentation:

https://docs.getml.com/latest/api/getml.feature_learning.aggregations.html

Also note that FastProp has a parameter `aggregation` which can either be `FastProp.agg_sets.Default`, `FastProp.agg_sets.Minimal` or `FastProp.agg_sets.All`.

Of course, you can also define your own aggregations sets.

https://docs.getml.com/latest/api/FastProp/getml.feature_learning.FastProp.agg_sets.html#getml.feature_learning.FastProp.agg_sets

**Comment by CapitalMarkets** [comment]
@liuzicheng1987 sorry for the late response - this is EXCELLENT NEWS and information.
I will study these references and experiment with the functionality.
Thank you VERY MUCH.  Will return with feedback if there are any issues :)
